# Generated by Django 4.2.29 on 2026-03-10 18:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name', max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth (must be 18+ years old)', null=True)),
                ('age', models.PositiveIntegerField(help_text='Age in years (calculated from date of birth)', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('religion', models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('buddhist', 'Buddhist'), ('jain', 'Jain'), ('other', 'Other')], default='', max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in feet (e.g., 5.6)', max_digits=4, null=True)),
                ('location', models.CharField(help_text='City, State, Country', max_length=255)),
                ('about', models.TextField(blank=True, help_text='About yourself')),
                ('desired_partner_traits', models.TextField(blank=True, help_text='Desired partner characteristics')),
                ('photo', models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='profile_photos/')),
                ('mobile_number', models.CharField(help_text='Mobile number with country code', max_length=15, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'users_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
