# Generated by Django 4.2.29 on 2026-03-25 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum preferred partner age', null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='age_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum preferred partner age', null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_education',
            field=models.CharField(blank=True, default='', help_text='Comma-separated preferred education levels', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='', help_text='Preferred partner gender', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_locations',
            field=models.CharField(blank=True, default='', help_text='Comma-separated preferred locations', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_religions',
            field=models.CharField(blank=True, default='', help_text='Comma-separated preferred religions', max_length=255),
        ),
    ]
