"""
URL configuration for users app.
Defines all API routes for user management, profiles, interests, reports, OTP, and exports.
"""

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)
from .views import (
    UserRegistrationView,
    UserListView,
    UserDetailView,
    CurrentUserView,
    ChangePasswordView,
    ProfileViewSet,
    OTPVerificationViewSet,
    InterestViewSet,
    FavoriteViewSet,
    ReportViewSet,
    ExportLogViewSet,
    FeedbackViewSet,
    CustomTokenObtainPairView,
    BlockUserView,
    PasswordResetRequestViewSet,
)

# App name for URL namespacing
app_name = 'users'

# Create router for viewsets
router = DefaultRouter()
router.register(r'profiles', ProfileViewSet, basename='profile')
router.register(r'otp', OTPVerificationViewSet, basename='otp')
router.register(r'interests', InterestViewSet, basename='interest')
router.register(r'favorites', FavoriteViewSet, basename='favorite')
router.register(r'reports', ReportViewSet, basename='report')
router.register(r'export-logs', ExportLogViewSet, basename='exportlog')
router.register(r'feedback', FeedbackViewSet, basename='feedback')
router.register(r'password-reset-requests', PasswordResetRequestViewSet, basename='password-reset-request')

urlpatterns = [
    # ============================================
    # JWT Authentication Endpoints
    # ============================================
    # Primary endpoints (as per standard convention) - with blocking check
    path('token/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    
    # Alternative endpoints for convenience (same functionality)
    path('auth/login/', CustomTokenObtainPairView.as_view(), name='auth_login'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='auth_refresh'),
    path('auth/verify/', TokenVerifyView.as_view(), name='auth_verify'),
    
    # ============================================
    # User Management Endpoints
    # ============================================
    path('register/', UserRegistrationView.as_view(), name='user-register'),
    path('users/', UserListView.as_view(), name='user-list'),
    path('users/me/', CurrentUserView.as_view(), name='current-user'),
    path('users/me/update/', UserDetailView.as_view(), name='user-update'),
    path('users/change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user-detail'),
    
    # ============================================
    # User Blocking Endpoints (Admin only)
    # ============================================
    path('users/<int:user_id>/block/', BlockUserView.as_view(), name='block-user'),
    
    # ============================================
    # ViewSet Routes (Auto-generated by Router)
    # ============================================
    # These include all CRUD operations for:
    # - /api/profiles/ (ProfileViewSet)
    # - /api/interests/ (InterestViewSet)
    # - /api/reports/ (ReportViewSet)
    # - /api/otp/ (OTPVerificationViewSet)
    # - /api/export-logs/ (ExportLogViewSet)
    path('', include(router.urls)),
    
    # ============================================
    # Export Endpoints (Admin Only)
    # ============================================
    # PDF Export
    path('export/profiles/pdf/', 
         ExportLogViewSet.as_view({'post': 'export_data'}), 
         name='export-profiles-pdf',
         kwargs={'file_type': 'pdf', 'export_type': 'profiles'}),
    
    # Excel Export
    path('export/profiles/excel/', 
         ExportLogViewSet.as_view({'post': 'export_data'}), 
         name='export-profiles-excel',
         kwargs={'file_type': 'excel', 'export_type': 'profiles'}),
    
    # Generic export endpoint (supports all types)
    path('export/<str:export_type>/<str:file_type>/',
         ExportLogViewSet.as_view({'post': 'export_data'}),
         name='export-generic'),
]

"""
Available Endpoints:

AUTHENTICATION (Primary):
    POST   /api/token/                      - Login and get JWT tokens
    POST   /api/token/refresh/              - Refresh access token
    POST   /api/token/verify/               - Verify token validity

AUTHENTICATION (Alternative - same functionality):
    POST   /api/auth/login/                 - Login and get JWT tokens
    POST   /api/auth/refresh/               - Refresh access token
    POST   /api/auth/verify/                - Verify token validity

USER MANAGEMENT:
    POST   /api/users/register/             - Register new user
    GET    /api/users/users/                - List all users
    GET    /api/users/users/me/             - Get current user
    PUT    /api/users/users/me/update/      - Update current user
    DELETE /api/users/users/me/update/      - Delete current user
    PUT    /api/users/users/change-password/ - Change password
    GET    /api/users/users/{id}/           - Get user by ID

PROFILES:
    GET    /api/users/profiles/             - List all profiles
    POST   /api/users/profiles/             - Create profile
    GET    /api/users/profiles/{id}/        - Get profile by ID
    PUT    /api/users/profiles/{id}/        - Update profile
    DELETE /api/users/profiles/{id}/        - Delete profile
    GET    /api/users/profiles/me/          - Get my profile
    POST   /api/users/profiles/create-mine/ - Create my profile
    GET    /api/users/profiles/{id}/view/   - View profile details

INTERESTS:
    GET    /api/users/interests/            - List interests
    POST   /api/users/interests/            - Send interest
    GET    /api/users/interests/{id}/       - Get interest by ID
    PUT    /api/users/interests/{id}/       - Update interest
    DELETE /api/users/interests/{id}/       - Delete interest
    GET    /api/users/interests/sent/       - Get sent interests
    GET    /api/users/interests/received/   - Get received interests
    GET    /api/users/interests/pending/    - Get pending interests
    POST   /api/users/interests/{id}/respond/ - Accept/reject interest
    POST   /api/users/interests/{id}/cancel/  - Cancel interest

REPORTS:
    GET    /api/users/reports/              - List reports
    POST   /api/users/reports/              - Create report
    GET    /api/users/reports/{id}/         - Get report by ID
    PUT    /api/users/reports/{id}/         - Update report
    DELETE /api/users/reports/{id}/         - Delete report
    GET    /api/users/reports/my-reports/   - Get my reports
    GET    /api/users/reports/pending/      - Get pending reports (Admin)
    POST   /api/users/reports/{id}/review/  - Review report (Admin)
    GET    /api/users/reports/statistics/   - Get statistics (Admin)

OTP VERIFICATION:
    GET    /api/users/otp/                  - List OTP history
    POST   /api/users/otp/generate/         - Generate OTP
    POST   /api/users/otp/verify/           - Verify OTP
    POST   /api/users/otp/resend/           - Resend OTP

EXPORTS (Admin Only):
    POST   /api/users/export/profiles/pdf/  - Export profiles as PDF
    POST   /api/users/export/profiles/excel/ - Export profiles as Excel
    POST   /api/users/export/{type}/{format}/ - Generic export endpoint
    GET    /api/users/export-logs/          - List export logs
    POST   /api/users/export-logs/export-data/ - Export data

Query Parameters:
    - Profiles: gender, min_age, max_age, location, search, ordering
    - Interests: type (sent/received), status (pending/accepted/rejected)
    - Reports: status (pending/reviewed/resolved)
    - Export Logs: admin_id, file_type, export_type
"""
