# Generated by Django 4.2.29 on 2026-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show this feedback as a public testimonial'),
        ),
    ]
