from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone


class User(AbstractUser):
    """Custom User model with admin, blocking, and subscription fields."""

    SUBSCRIPTION_SILVER = 'silver'
    SUBSCRIPTION_GOLD = 'gold'
    SUBSCRIPTION_CHOICES = [
        (SUBSCRIPTION_SILVER, 'Silver'),
        (SUBSCRIPTION_GOLD, 'Gold'),
    ]

    subscription_type = models.CharField(
        max_length=10,
        choices=SUBSCRIPTION_CHOICES,
        default=SUBSCRIPTION_SILVER,
        help_text='Subscription level of the user.'
    )
    subscription_start = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the current subscription started.'
    )
    subscription_end = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the current subscription ends.'
    )

    deactivated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the account was deactivated.'
    )
    scheduled_deletion_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text='When the account is scheduled for permanent deletion.'
    )

    is_admin = models.BooleanField(
        default=False,
        help_text='Designates whether the user is an admin.'
    )
    is_blocked = models.BooleanField(
        default=False,
        help_text='Designates whether the user account is blocked by admin.'
    )
    blocked_reason = models.TextField(blank=True, null=True, help_text='Reason for blocking the account')
    blocked_at = models.DateTimeField(blank=True, null=True, help_text='Timestamp when the account was blocked')
    blocked_by = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='blocked_users', help_text='Admin who blocked this user'
    )

    class Meta:
        db_table = 'users_user'
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['-date_joined']

    def __str__(self):
        return self.username

    def ensure_subscription_valid(self, save=True):
        """Automatically downgrade expired Gold subscriptions to Silver."""
        if self.subscription_type == self.SUBSCRIPTION_GOLD and self.subscription_end:
            now = timezone.now()
            if self.subscription_end <= now:
                self.subscription_type = self.SUBSCRIPTION_SILVER
                self.subscription_start = None
                self.subscription_end = None
                if save:
                    self.save(update_fields=['subscription_type', 'subscription_start', 'subscription_end'])
        return self.subscription_type

    def has_active_gold_subscription(self):
        """Return True if the user currently has an active Gold subscription."""
        self.ensure_subscription_valid(save=True)
        if self.subscription_type != self.SUBSCRIPTION_GOLD:
            return False
        if not self.subscription_end:
            return False
        return self.subscription_end > timezone.now()


class PasswordResetRequest(models.Model):
    """Password reset requests submitted by users, processed by admins."""
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='password_reset_requests', help_text='User requesting password reset'
    )
    email = models.EmailField(help_text='Email address where new password will be sent')
    reason = models.TextField(blank=True, null=True, help_text='Reason for password reset request')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    admin_notes = models.TextField(blank=True, null=True, help_text='Admin notes regarding the request')
    processed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='processed_reset_requests', help_text='Admin who processed this request'
    )
    new_password = models.CharField(max_length=128, blank=True, null=True, help_text='Temporary password generated by admin')
    created_at = models.DateTimeField(auto_now_add=True)
    processed_at = models.DateTimeField(null=True, blank=True, help_text='When the request was processed')

    class Meta:
        db_table = 'users_passwordresetrequest'
        verbose_name = 'Password Reset Request'
        verbose_name_plural = 'Password Reset Requests'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username} - {self.status} - {self.created_at.strftime('%Y-%m-%d %H:%M')}"
