from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class User(AbstractUser):
    """Custom User model with admin and blocking fields."""
    is_admin = models.BooleanField(
        default=False,
        help_text='Designates whether the user is an admin.'
    )
    is_blocked = models.BooleanField(
        default=False,
        help_text='Designates whether the user account is blocked by admin.'
    )
    blocked_reason = models.TextField(blank=True, null=True, help_text='Reason for blocking the account')
    blocked_at = models.DateTimeField(blank=True, null=True, help_text='Timestamp when the account was blocked')
    blocked_by = models.ForeignKey(
        'self', on_delete=models.SET_NULL, null=True, blank=True,
        related_name='blocked_users', help_text='Admin who blocked this user'
    )

    class Meta:
        db_table = 'users_user'
        verbose_name = 'User'
        verbose_name_plural = 'Users'
        ordering = ['-date_joined']

    def __str__(self):
        return self.username


class PasswordResetRequest(models.Model):
    """Password reset requests submitted by users, processed by admins."""
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('rejected', 'Rejected'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='password_reset_requests', help_text='User requesting password reset'
    )
    email = models.EmailField(help_text='Email address where new password will be sent')
    reason = models.TextField(blank=True, null=True, help_text='Reason for password reset request')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    admin_notes = models.TextField(blank=True, null=True, help_text='Admin notes regarding the request')
    processed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='processed_reset_requests', help_text='Admin who processed this request'
    )
    new_password = models.CharField(max_length=128, blank=True, null=True, help_text='Temporary password generated by admin')
    created_at = models.DateTimeField(auto_now_add=True)
    processed_at = models.DateTimeField(null=True, blank=True, help_text='When the request was processed')

    class Meta:
        db_table = 'users_passwordresetrequest'
        verbose_name = 'Password Reset Request'
        verbose_name_plural = 'Password Reset Requests'
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.user.username} - {self.status} - {self.created_at.strftime('%Y-%m-%d %H:%M')}"
