# Generated by Django 4.2.29 on 2026-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateTimeField(blank=True, help_text='When the current subscription ends.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_start',
            field=models.DateTimeField(blank=True, help_text='When the current subscription started.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[('silver', 'Silver'), ('gold', 'Gold')], default='silver', help_text='Subscription level of the user.', max_length=10),
        ),
    ]
