# Generated by Django 4.2 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_subscription_end_user_subscription_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
