# Generated by Django 4.2.29 on 2026-03-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_deactivated_at_user_scheduled_deletion_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the account was deactivated.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, help_text='When the account is scheduled for permanent deletion.', null=True),
        ),
    ]
