# Generated by Django 4.2.25 on 2025-10-15 15:43

from django.db import migrations, models


def update_other_gender_profiles(apps, schema_editor):
    """
    Update any profiles with 'other' gender to be unspecified.
    Since we're removing 'other' as a choice, we'll update them to
    'male' as a default. Users can update this in their profile later.
    """
    Profile = apps.get_model('users', 'Profile')
    # Update all profiles with 'other' gender to 'male' (users will update later)
    Profile.objects.filter(gender='other').update(gender='male')


def reverse_update_gender(apps, schema_editor):
    """
    Reverse migration - do nothing as we can't know what the original values were.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_other_gender'),
    ]

    operations = [
        migrations.RunPython(update_other_gender_profiles, reverse_update_gender),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(
                max_length=10,
                choices=[('male', 'Male'), ('female', 'Female')]
            ),
        ),
    ]
