# Generated by Django 4.2.25 on 2025-11-20 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_date_of_birth_alter_profile_age_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the account was blocked', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_by',
            field=models.ForeignKey(blank=True, help_text='Admin who blocked this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.TextField(blank=True, help_text='Reason for blocking the account', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Designates whether the user account is blocked by admin.'),
        ),
    ]
