# Generated by Django 4.2.25 on 2025-11-20 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_blocked_at_user_blocked_by_user_blocked_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address where new password will be sent', max_length=254)),
                ('reason', models.TextField(blank=True, help_text='Reason for password reset request', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of the request', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes regarding the request', null=True)),
                ('new_password', models.CharField(blank=True, help_text='Temporary password generated by admin', max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the request was processed', null=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin who processed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reset_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting password reset', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
                'db_table': 'users_passwordresetrequest',
                'ordering': ['-created_at'],
            },
        ),
    ]
